fix(actions): adjust requirements installation (#259)
Move the version prefix `v` of grype and sbomqs environment variables
into the url during the install step, because in renovate updates
might remove this prefix when it created a pull request (see #256).

Also verify the checksum of the downloaded grype and sbomqs files.

---------

Co-authored-by: Florian Heubeck <40993644+heubeck@users.noreply.github.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -11,8 +11,8 @@ concurrency:
 env:
     CDXGEN_VERSION: '9.9.6'
     CDXGEN_PLUGINS_VERSION: '1.4.0'
-    GRYPE_VERSION: 'v0.73.4'
-    SBOMQS_VERSION: 'v0.0.27'
+    GRYPE_VERSION: '0.73.4'
+    SBOMQS_VERSION: '0.0.27'
     semantic_version: '19.0.5'
     java_version: '21'
     mvn_parameter: '-B -ntp'
@@ -49,19 +49,32 @@ jobs:
 
             - name: Install requirements
               run: |
-                  # cdxgen
+                  echo "Install cdxgen"
                   npm install -g @cyclonedx/cdxgen@${CDXGEN_VERSION}
                   npm install -g @cyclonedx/cdxgen-plugins-bin@${CDXGEN_PLUGINS_VERSION}
 
                   mkdir _bin
                   echo $(pwd)/_bin >> $GITHUB_PATH
 
-                  # grype
-                  curl -Ls https://github.com/anchore/grype/releases/download/${GRYPE_VERSION}/grype_${GRYPE_VERSION:1}_linux_amd64.tar.gz -o grype.tar.gz
+                  echo "Install grype"
+                  GRYPE_URL="https://github.com/anchore/grype/releases/download/v${GRYPE_VERSION}"
+                  curl -Ls "$GRYPE_URL/grype_${GRYPE_VERSION}_linux_amd64.tar.gz" -o grype.tar.gz
+                  curl -Ls "$GRYPE_URL/grype_${GRYPE_VERSION}_checksums.txt" -o grype_checksums.txt
+                  if ! grep -q "$(sha256sum grype.tar.gz | cut -d' ' -f1)" grype_checksums.txt; then
+                      echo "::error title=Invalid checksum::grype ${GRYPE_VERSION}"
+                      exit 1
+                  fi
                   tar xf grype.tar.gz -C _bin
 
-                  # sbomqs
-                  curl -Ls https://github.com/interlynk-io/sbomqs/releases/download/${SBOMQS_VERSION}/sbomqs-linux-amd64 -o _bin/sbomqs
+                  echo "Install sbomqs"
+                  SBOMQS_URL="https://github.com/interlynk-io/sbomqs/releases/download/v${SBOMQS_VERSION}"
+                  curl -Ls "$SBOMQS_URL/sbomqs-linux-amd64" -o sbomqs
+                  curl -Ls "$SBOMQS_URL/sbomqs_${SBOMQS_VERSION}_checksums.txt" -o sbomqs_checksums.txt
+                  if ! grep -q "$(sha256sum sbomqs | cut -d' ' -f1)" sbomqs_checksums.txt; then
+                      echo "::error title=Invalid checksum::sbomqs ${SBOMQS_VERSION}"
+                      exit 1
+                  fi
+                  mv sbomqs _bin/sbomqs
                   chmod a+x _bin/sbomqs
 
             - name: Application Build and Test
